### PR TITLE
Added installer tools and logic--fix #97

### LINKED ISSUE #97: Update/Delete of app
In order to update and delete previous versions, the path for the appium module will need to be minified, so as NOT to exceed the windows max path limit size, before deletion. 

Will need to write a module for this.

### PR DESCRIPTION
**Pull request by 0x1mason**
This commit adds tools to create an installer for appium-dot-exe.  It also tweaks the release post-build events to use the tools to build the installer.  The installer uses 7zr.exe to extract the modules on install, thereby working around path length limitations (ie #97).

Since this can install to Prog Files, it changes permission scenarios (tho it gives users full rights to node_modules). You can no longer assume users have write permissions to the root dir.  That shouldn't really be a problem moving forward since the installer automatically requests admin privs, but may require some changes to the way you're updating now (see http://www.jrsoftware.org/ishelp/topic_setup_appid.htm and http://www.jrsoftware.org/ishelp/index.php?topic=technotes). You can change the permissions and default install locations in the inno setup .iss file if needed.

Most of these files are for the new tools.  The ones you'll want to review are:
* .gitignore
* AppiumWPF/AppiumWPF.csproj
* installer/Appium-dot-exe.iss

### CODE REVIEW

**Comment by Astro03** [comment]
Awesome. I'll look at this tomorrow . Thanks for doing this, i haven't had the time to do the 7z swap. 

Thanks,
ASTRO

**Comment by jlipps** [comment]
awesome! \o/

**Comment by Astro03** [comment]
@0x1mason - can you do a clean pull of your pull request and try to rebuild? I had to echo out all your post build steps to be able to compile. Don't know which items you want to keep in there so can you take a look at that? Thx. I'm looking at the other parts right now  :)

**Comment by Astro03** [comment]
@0x1mason - i'm a bit out of my breath here, I've never done a setup like this. But just from looking at the code, it doesn't appear that the last line of your post build is working (the inno setup line).

**Comment by 0x1mason** [comment]
@Astro03 If you do a clean build, is there nothing in <root>\installer?

**Comment by 0x1mason** [comment]
or no `appium-installer.exe`?

**Comment by 0x1mason** [comment]
@Astro03 nm, I think I've repro'd the issue.

**Comment by Astro03** [comment]
@0x1mason  approve me on fb and we can chat on there easier.. :)  and yea,, download a clean version of your pull.. then try a rebuild and it won't work.

**Comment by bootstraponline** [comment]
@Astro03 I sent you an invite to the appium Slack chat.

**Comment by Astro03** [comment]
@bootstraponline where did you send the invite to?

**Comment by bootstraponline** [comment]
@Astro03 to `locopelon03@hotmail.com` which is the email listed on your github profile. Is there a different email I should use?

**Comment by 0x1mason** [comment]
@Astro03 everything should be working now.  The installer does not build on debug config.

**Comment by Astro03** [comment]
looks great. and the installer works wonderfully.

**Pull request merged**
